version: '3'

services:
  postgres:
    restart: always
    image: postgres:9.6.6
    env_file:
      - osm-docker.env
    volumes:
      - ./website/openstreetmap-website:/openstreetmap-website
      - ./postgres/scripts:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  rendering_database:
    restart: always
    build:
      context: ./rendering_database
      dockerfile: ./Dockerfile
    links:
      - postgres
    env_file:
      - osm-docker.env
    volumes:
      - ./rendering_database/scripts:/docker-entrypoint-initdb.d
      - ./rendering_database/data:/var/lib/postgresql/data
      - ./rendering_database/config:/config

  website:
    restart: always
    build:
      context: ./website
      dockerfile: ./Dockerfile
    volumes:
      - ./website/openstreetmap-website:/openstreetmap-website
      - ./website/scripts:/scripts
    env_file:
      - osm-docker.env
    ports:
      - 3000:3000
    links:
      - postgres
    command: /bin/bash /scripts/start_server.sh
