version: '3'

services:
  website:
    restart: always
    build:
      context: ./website
      dockerfile: ./Dockerfile
    volumes:
      - ./website/openstreetmap-website:/openstreetmap-website
    env_file:
      - osm-docker.env

  cgimap:
    restart: always
    build:
      context: ./cgimap
      dockerfile: ./Dockerfile
    env_file:
      - osm-docker.env
    tty: true

  nginx:
    restart: always
    image: nginx:1.13.8-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - osm-docker.env
    ports:
      - 3000:80
