version: '3'

services:
  postgres:
    image: postgres:9.6
    env_file:
      - osm-docker.env
    volumes:
      - ./website/openstreetmap-website:/openstreetmap-website
      - ./postgres/scripts:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  website:
    restart: always
    build:
      context: ./website
      dockerfile: ./Dockerfile
    volumes:
      - ./website/openstreetmap-website:/openstreetmap-website
      - ./website/scripts:/scripts
    env_file:
      - osm-docker.env
    ports:
      - 3000:3000
    links:
      - postgres
    command: /bin/bash /scripts/start_server.sh
