version: '3'
services:
  postgres:
    image: postgres:10
  website:
    restart: always
    build:
      context: ./website
      dockerfile: ./Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/openstreetmap-website
    environment:
      RAILS_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - postgres
